# Generated by Django 4.0.3 on 2023-06-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_slug_alter_auction_id_alter_bid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
