# Generated by Django 4.0.3 on 2023-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
