# Generated by Django 4.0.3 on 2023-07-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
