# Generated by Django 4.2.3 on 2023-08-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_user_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-id']},
        ),
    ]
