# Generated by Django 4.2.3 on 2023-08-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='auction',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='auctions.auction'),
        ),
    ]
