# Generated by Django 4.2.3 on 2023-08-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_category_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='auction',
            field=models.ManyToManyField(related_name='categories', to='auctions.auction'),
        ),
    ]
